### ISSUE TITLE
ACI fault code F1128 raised when service_graph is null

### ISSUE THREAD

**Issue by andbyrne** [netascode/terraform-aci-contract#3]
This code will generate a vzRsSubjGraphAtt object with no value for its tnVnsAbsGraphName attribute if no service_graph input is provided. A fault code F1128 is raised as a result.

The required action is to only create the object if service_graph is not null/empty.

**Comment by danischm** [comment]
https://github.com/netascode/terraform-aci-contract/commit/f7873ac68d4a890884871ab2e0d3d592927a6ea1

**Comment by danischm** [comment]
https://github.com/netascode/terraform-aci-contract/releases/tag/v0.1.1
